# Generated by Django 3.2 on 2021-05-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_pass_end_date'),
        ('payments', '0007_alter_transaction_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pass_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pass', to='myapp.pass'),
        ),
    ]
