# Generated by Django 3.2 on 2021-05-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20210529_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
