# Generated by Django 3.2 on 2021-06-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_transaction_amount'),
        ('payments', '0008_transaction_pass_id'),
    ]

    operations = [
    ]
