# Generated by Django 3.2 on 2021-04-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passid',
            name='pass_charges',
            field=models.IntegerField(default=50),
        ),
    ]
