# Generated by Django 3.2 on 2021-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile_pic',
            field=models.FileField(default='pic.jpg', upload_to='profile_pic'),
        ),
    ]
