# Generated by Django 3.2 on 2021-04-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pass_valid',
        ),
    ]
