# Generated by Django 3.2 on 2021-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Profile_pic',
            field=models.FileField(default='pic.jpg', upload_to='profile_pic'),
        ),
    ]
