# Generated by Django 3.2 on 2021-05-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify',
        ),
    ]
