# Generated by Django 3.2 on 2021-05-27 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passid',
            name='u_id',
        ),
        migrations.RenameField(
            model_name='pass',
            old_name='pass_issue_date',
            new_name='End_date',
        ),
        migrations.RenameField(
            model_name='pass',
            old_name='pass_amount',
            new_name='Pass_amount',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='pass_duration',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='source',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_handicaped',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verify',
        ),
        migrations.AddField(
            model_name='pass',
            name='Destination',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='Distance',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='Duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='From',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='Issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pass',
            name='To',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='LocationDestination',
        ),
        migrations.DeleteModel(
            name='LocationSource',
        ),
        migrations.DeleteModel(
            name='PassId',
        ),
    ]
