# Generated by Django 3.2 on 2021-05-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210527_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='End_date',
            field=models.DateField(),
        ),
    ]
