# Generated by Django 3.2 on 2021-06-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_pass_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='Issue_date',
            field=models.DateField(),
        ),
    ]
