# Generated by Django 3.2 on 2021-06-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_pass_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='End_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='Issue_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
